src/https_client.c
The latest libcurl for 16.04 LTS is based on curl 7.47.0 and does not include `CURLINFO_HTTP_VERSION` and `CURLINFO_PROTOCOL which were released in curl 7.50.0 and 7.52.0, respectively.
=> Only use things from non-LTS libcurl if they are defined

src/https_client.c
According to the man page, curl_multi_socket_action's ev_bitmask argument takes
CURL_CSELECT_IN, CURL_CSELECT_OUT or CURL_CSELECT_ERR, not the CURL_POLL_* ones
that the callbacks take.  They happen to be the same values at the moment, though.
=> Use correct args to curl_multi_socket_action.

src/logging.c, src/logging.h, src/main.c
When debug logging is enabled debug-level messages are not flushed,
presumably to keep the overhead down.  This means that debug messages
can end up not being shown until either a more severe error happens or
the server gets shut down.  This adds a timer that flushes the log
every ten seconds.  (This is set up after logging_init since the log
may be needed during the event loop setup.)
Fixes https://github.com/aarond10/https_dns_proxy/issues/19
=> Add a timer to flush the debug log.

src/https_client.c
Some older libcurls don't have CURLMOPT_PIPELINING, so check that it's
defined before trying to use it.
=> Only set pipelining if libcurl supports it.

README.md, src/logging.c, src/logging.h, src/main.c
Log messages of severity WARNING or higher are always flushed after
being written, so if we do not emit messages below that severity (which
is the common case) then there is no need for the periodic flush calls.
=> Avoid log flush timer where possible.

README.md, src/main.c, src/options.c
Many of the protocols supported by libcurl support remote name
resolution.  When those are in use, do not attempt local resolution of
dns.google.com and instead leave it to the proxy to resolve.  This may
result in better performance if the proxy gets a closer address for
the server.
See https://github.com/aarond10/https_dns_proxy/issues/12
=> Use proxy remote name resolution if possible.

src/dns_poller.c, src/dns_poller.h, src/main.c
The current behavior is a fixed 120 second interval. On some setups,
such as OpenWrt, this leads to a long delay before DNS queries can be
serviced because the daemon may be started before the WAN interface is
operational, leading to an immediate failure of the initial bootstrap
lookup.
Depending on the host's configuration, this can cause a DNS loop, where
libcurl falls back to resolv.conf (127.0.0.1 in some setups), leading to
situations like:
https_dns_proxy -> dnsmasq -> https_dns_proxy -> ...
https_dns_proxy -> https_dns_proxy -> ...
Only after the 120 seconds has elapsed and the provided resolver
hostname (dns.google.com, cloudflare-dns.com, etc.) is finally resolved
would DNS begin to function.
To work around this, ares_cb() has been modified to adjust the bootstrap
interval …
=> Dynamically adjust DNS bootstrap interval during runtime

CMakeLists.txt
On Ubuntu 19.04, the previous way of doing things caused build errors
due to the lack of -lpthread. While explicitly adding
find_package(Threads) worked as well, this seems like a better option.
This also fixes an issue on Debian Jessie where the build would fail if
gtest.h exists but libgtest.a does not. Jessie only includes the
source files with the libgtest-dev package, and requires manually
building libgtest.a after installation.
Signed-off-by: Matt Merhar <mattmerhar@protonmail.com>
=> Use FindGTest to search for googletest

README.md, src/options.c, src/options.h
Reference for URL change: https://developers.google.com/speed/public-dns/docs/doh/migration#dns-google
I haven't updated the comments about "alternative protocols", but I suspect you'd like the new [RFC 8484](https://tools.ietf.org/html/rfc8484).
=> Update links to point at dns.google; clarify that this is for the JSON API

src/dns_server.c
This changes the DNS request deserialisation code to read the `uint16`s out of the buffer without violating strict aliasing rules, which could cause crashes platforms where unaligned memory access results in a fault, or bugs where the compiler decides to take liberty with the undefined behaviour of the original code (there shouldn't be any difference in the generated assembly, as `next_uint16()` should be inlined).
=> Source changes to avoid strict aliasing violations and uninitialised memory reads

src/options.c
Log level is controlled by the number of '-v' options passed in cmdline,
however there's nothing to stop the log level going negative.
Fortunately because the log level is currently a signed type the
comparison of < message level works.  Let's limit to 0.
Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>
=> options: stop loglevel going negative

src/dns_poller.c, src/dns_poller.h, src/dns_server.c, src/dns_server.h, src/main.c, src/options.c
Now complete.
* IPv6 bootstrap server support, using `ares_set_servers_csv_ports` instead of manually parsing the list
* IPv6 client support, using `getaddrinfo` to get the listen addr, but numeric only (`AI_NUMERICHOST`)
Tested on Ubuntu, WSL, OpenWRT, untested on *BSDs (yet).
=> Full IPv6 support

README.md
`cmake .` step is failing on unable to find GTest:
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
- on Fedora its package gtest-devel
- on Debian i'm just guessing based on web search that it could be libgtest-dev?
=> Mention gtest in build deps

README.md
I was testing https_dns_proxy using a [LXD](https://linuxcontainers.org/lxd/) container and had an issue.  I was getting an error when running the `cmake .` step:
```
CMake Error at CMakeLists.txt:1 (project):
No CMAKE_CXX_COMPILER could be found.
```
The fix was to add `build-essential` to the `apt-get install` line. Adding this should be harmless as [it installs the things needed](https://packages.ubuntu.com/bionic/build-essential) to make the software, which is what we want ;)
Here's a complete copy of my session creating a container from scratch, cloning this repo, `apt-get install`ing, getting the error, installing  `build-essential` and then not getting the error.
-------------------
```
➜  ~ lxc launch ubuntu: doh2               
Creating doh2
Starting doh2
➜  ~ lxc exec doh2 -- …
```
=> add build-essential to ubuntu instructions

README.md, src/https_client.c, src/options.c, src/options.h
Specify a DSCP codepoint on DNS server upstream connections.  This may
be useful to those using qdiscs/AQMs that categorise traffic
importance/priority by DSCP value.
Whilst this could be done by ip/nftables rules, let's get the
application to do it.
Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>
=> Add -c DSCP codepoint option

README.md
Aaron, this includes updated OpenWrt instructions. Sorry it took me that long to submit.
PS. The OpenWrt package was renamed from https_dns_proxy to https-dns-proxy when principal package switched from JSON to RFC8484 support which required a new config file for OpenWrt.
Signed-off-by: Stan Grishin <stangri@melmac.net>
=> https_dns_proxy: update README

README.md
I created a pretty basic Dockerfile that pulls from your repo and builds.  I expose value-based flags as environment variables (i.e. DNS_SERVERS) and pure flags as cmd arguments (i.e. -4).
Perhaps running in a container is a fringe use case, but it seems to work well.
https://github.com/moranbw/https-dns-proxy-docker
=> Update documentation to reference Docker install.

README.md
As mentioned in #103, link for Docker Image was incorrect.  Fixed to public link now.
Sorry for the mishap!
=> Fix link for "Docker image" in README.md

src/dns_poller.c, src/dns_server.c, src/https_client.c, src/main.c, src/options.c
Hi, I found the `strerror()` cannot work properly to return the information corresponded to the errno value (segmentation fault).
Therefore, I add the `<string.h>` header for solving the build warning and the more important thing is to fix the segmentation fault as `stderror`'s result requires `string.h` included.
Ref:
https://stackoverflow.com/questions/17174081/why-cant-the-result-of-strerror-be-returned
https://stackoverflow.com/questions/47112630/segmentation-fault-when-print-errno-for-shm-open-in-linux
=> Fix segmentation fault by adding missing <string.h>

src/https_client.c
If HTTP/2 is unsupported by libcurl, force HTTP/1.1
This will prevent log flood, by printing log only in case of first request.
Tested by changing CURL_HTTP_VERSION_2_0 to invalid randum number
and sending in multiple requests at the same time, so new HTTP
session open would be needed.
Fix for: #115
=> Prevent error log flood if HTTP/2 is unsupported

src/dns_poller.c, src/dns_server.c, src/https_client.c, src/https_client.h, src/logging.h, src/main.c, src/stat.h
Hi,
For now this is my last pack of changes.
Even I hope, that there won't be any more huge patches from me :D
Now seriously:
- I have created a function to proxy curl debug info, so it could be logged with own logging macros.
- DNS request ID is printed at the beginning of every line, so if multiple requests are processed at the time it's easier to distinguish them.
Br,
Balázs
=> Request debug logging improvement

.github/workflows/cmake.yml, CMakeLists.txt, munin/https_dns_proxy.plugin, src/https_client.c, src/logging.h, src/options.c
Hi,
here we go again:
1. To skip C++ compiler check by cmake the project language is set to only C
2. clang-tidy finding fixes
3. Fixed munin plugin, because in case of internet outage (BASH_REMATCH variable was cleared by error logs and) graph was not made
4. Using macro to cast and check pointer in https_client.c (I don't like macros, but it's less line this way...)
5. Fixed --help a bit
6. Because of #123 a new error message was added to help clients with debugging if DNS resolving does not work
As always: I have tested my changes in my own server.
I hope, you will like it.
Sincerely,
Balázs
=> Fixes and improvements 6

README.md
Yaourt is long past being recommended. If the user must use an AUR helper yay is much better for many reasons documented on the Arch Wiki.
=> Recommend a different AUR helper

CMakeLists.txt
A very minor change. This PR allows building using CMake in a subdirectory, as customary not to pollute the main project folder with temporary build files, like so:
```
mkdir build
cd build
cmake ..
make
sudo make install
```
Currently the install step fails, as it understands the .service file is specified relative to the source folder:
```
marcos@raspberrypi:~/https_dns_proxy/build $ sudo make install
[sudo] password for marcos:
[100%] Built target https_dns_proxy
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/bin/https_dns_proxy
CMake Error at cmake_install.cmake:70 (file):
file INSTALL cannot find
"/home/marcos/https_dns_proxy/https_dns_proxy.service": No such file or directory.
make: *** [Makefile:126: install] Error 1
```
This only adds the …
=> Allow building in another directory

src/https_client.c, src/options.c, src/options.h
This adds a commandline option to pass additional CA certificates through to curl.
=> Option to pass CA_INFO through to curl

CMakeLists.txt
This is so that flags set for thing like sysroot are used when cross compiling
=> Don't discard externally set C_FLAGS

src/logging.h, src/main.c
Hi, this change fixes #160 
Beside that I would recommend to close all the current issues. I think all of them are answered or we have nothing to do with them.
=> Rewritten hostname extraction from resolver URL

CMakeLists.txt
Specifying -DUSE_CLANG_TIDY=OFF during compilation will disable clang-tidy.
=> Allow clang-tidy to be disabled during compilation

src/dns_poller.c
This import does not seem to be required, and causes compilation issues in a Buildroot ARM64 environment during clang-tidy
=> Remove unnecessary math.h import

src/https_client.c
According to the switch-case, it is clear that the intended output here is `curl_result_code` rather than `res`, because the value of `res` is always 0.
=> Fix `curl_result_code` log

src/https_client.c
On some types of errors (e.g. early connection failures), `CURLINFO_EFFECTIVE_URL` and `CURLINFO_SCHEME` might not ever get set, resulting in a segfault when trying to acces their contents.
=> Fix missing null checks when debug logging request information

.github/workflows/cmake.yml, .gitignore, CMakeLists.txt, README.md, https_dns_proxy.service.in, munin/https_dns_proxy.plugin, src/dns_poller.c, src/dns_poller.h, src/dns_server.c, src/dns_server.h, src/dns_server_tcp.c, src/dns_server_tcp.h, src/https_client.c, src/https_client.h, src/logging.c, src/main.c, src/options.c, src/options.h, src/stat.c, src/stat.h, tests/robot/DnsTcpClient.py, tests/robot/functional_tests.robot
Hi Aaron,
I hope you are doing well! I suppose you won't like me now. I have a lot of things for review.
Content list:
1. TCP support to fix #186 
2. UDP reply truncation feature to fix #184
3. Code quality stuff: more compiler warnings and warning fixes
4. c-ares API modernization
5. Reset HTTPS connection to avoid half-open TCP problems to fix #189 
6. systemd improvements (mostly for my Ubuntu server)
7. Version bump (I guess it is time)
@stangri it I may ask, please remove file https://github.com/openwrt/packages/blob/master/net/https-dns-proxy/patches/010-cmakelists-remove-cflags.patch if you would uplift the OpenWRT package after this pull request would be merged. I have compiled the OpenWRT package myself and I have not met any warnings. If there would be, please let me know. …
=> Large improvement pack
